<?php
// $Id$

define('CONGLOMERATE_SYNCHRONIZED', 0);
define('CONGLOMERATE_NODE_ADDED', 1);
define('CONGLOMERATE_NODE_UPDATED', 2);
define('CONGLOMERATE_NODE_REMOVED', 2);

define('CONGLOMERATE_TYPE_NONE', 'none');
define('CONGLOMERATE_TYPE_POST', 'post');
define('CONGLOMERATE_TYPE_EVENT', 'event');

function conglomerateclient_perm() {
  return array('administer conglomerate client');
}

/**
 * Implementation of hook_views_api().
 */
function conglomerateclient_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'conglomerateclient') . '/views',
  );
}
