<?php
// $Id$

define('CONGLOMERATE_CREATE', 'create');
define('CONGLOMERATE_UPDATE', 'update');
define('CONGLOMERATE_DELETE', 'delete');

define('CONGLOMERATE_TYPE_NONE', 'none');
define('CONGLOMERATE_TYPE_POST', 'news');
define('CONGLOMERATE_TYPE_EVENT', 'event');
define('CONGLOMERATE_TYPE_LOCATION', 'location');

/**
 * Implementation of hook_perm().
 */
function conglomerateclient_perm() {
  return array('administer conglomerate client');
}

/**
 * Implementation of hook_menu().
 */
function conglomerateclient_menu() {
  $menu = array();

  $menu['conglomerate/login'] = array(
    'title' => 'Login',
    'file' => 'includes/login.inc',
    'page callback' => '_conglomerateclient_login',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $menu['admin/settings/conglomerateclient'] = array(
    'title'   => 'Conglomerate client settings',
    'description' => 'Administer the settings for the conglomerate client',
    'file'  => 'includes/admin.inc',
    'page callback' => '_conglomerateclient_admin_index',
    'access arguments' => array('adminster conglomerate client'),
    'type'    => MENU_NORMAL_ITEM,
  );

  $menu['admin/settings/conglomerateclient/index'] = array(
    'title' => 'Conglomerate servers',
    'type'    => MENU_DEFAULT_LOCAL_TASK,
    'weight'  => -10,
  );

  $menu['admin/settings/conglomerateclient/add_server'] = array(
    'title' => 'Add server',
    'file'  => 'includes/admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_conglomerateclient_admin_add_server'),
    'access arguments' => array('adminster conglomerate client'),
    'type'    => MENU_LOCAL_TASK,
  );

  $menu['admin/settings/conglomerateclient/server/%'] = array(
    'title callback' => '_conglomerateclient_server_name_callback',
    'title arguments' => array(4, 'Edit server !name'),
    'file' => 'includes/admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_conglomerateclient_admin_edit_server', 4),
    'access arguments' => array('administer conglomerate client'),
    'type' => MENU_LOCAL_TASK,
  );

  $menu['admin/settings/conglomerateclient/server/%/export'] = array(
    'title callback' => '_conglomerateclient_server_name_callback',
    'title arguments' => array(4),
    'file'  => 'includes/admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_conglomerateclient_admin_export_server', 4),
    'access arguments' => array('adminster conglomerate client'),
    'type'    => MENU_CALLBACK,
  );

  $menu['admin/settings/conglomerateclient/authorize/%'] = array(
    'file'  => 'includes/authorization.inc',
    'page callback' => '_conglomerateclient_authorize_for_server',
    'page arguments' => array(4),
    'access arguments' => array('adminster conglomerate client'),
    'type'    => MENU_CALLBACK,
  );

  return $menu;
}

function conglomerateclient_form_user_login_alter(&$form, $form_state) {
  $sid = variable_get('conglomerateclient_login_server', 1);
  $servers = conglomerateclient_get_servers();

  if (!empty($servers[$sid])) {
    $server = $servers[$sid];
    if (!empty($server['login_oauth_consumer'])) {
      $form['conglomerate_login'] = array(
        '#value' => l(t('Log in using !name', array(
          '!name' => $server['name'],
        )), 'conglomerate/login'),
        '#prefix' => '<p class="conglomerate-login-link">',
        '#suffix' => '</p>',
        '#weight' => -10,
      );
    }
  }

}

function _conglomerateclient_server_name_callback($sid, $title = NULL) {
  $servers = conglomerateclient_get_servers();
  if (isset($servers[$sid])) {
    return empty($title) ? $servers[$sid]['name'] : t($title, array('!name' => $servers[$sid]['name']));
  }
}

/**
 * Implementation of hook_theme().
 */
function conglomerateclient_theme($existing, $type, $theme, $path) {
  $themes = array();

  $themes['conglomerateclient_admin_index'] = array(
    'template' => 'conglomerateclient_admin_index',
    'path' => $path . '/templates',
    'arguments' => array(
      'servers' => array(),
      'messages' => array(),
    ),
  );

  $themes['conglomerate_nearby_links'] = array(
    'template' => 'conglomerate_nearby_links',
    'path' => $path . '/templates',
    'arguments' => array(
      'items' => array(),
    ),
  );

  $themes['conglomerateclient_formatter_export_time'] = array(
    'arguments' => array('element' => NULL),
    'function' => 'theme_conglomerateclient_formatter_export_time',
  );

  return $themes;
}

/**
 * Implementation of hook_views_api().
 */
function conglomerateclient_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'conglomerateclient') . '/views',
  );
}

/**
 * Implementation of hook_oauth_common_authorized().
 */
function conglomerateclient_oauth_common_authorized($consumer_token, $access_token, $request_token) {
  if ($_SESSION['conglomerate_login_request_key'] == $request_token->key) {
    $res = db_query("SELECT * FROM {conglomerateclient_server}
      WHERE login_oauth_consumer='%s'", array(
        ':login_oauth_consumer' => $consumer_token->key,
      ));
    $login_server = db_fetch_array($res);
    if ($login_server) {
      require_once('includes/login.inc');
      $auth = new RestClientOAuth($consumer_token, $access_token, new OAuthSignatureMethod_HMAC('sha1'));
      $client = new RestClient($auth, new RestClientBaseFormatter(RestClientBaseFormatter::FORMAT_PHP));

      $external_user = (array)$client->post(sprintf('%slogin-api/user/info.php', $consumer_token->provider_url), array());
      _conglomerateclient_login_external_user($external_user);
    }
  }
  else if (user_access('adminster conglomerate client')) {
    $res = db_query("SELECT * FROM {conglomerateclient_server}
      WHERE oauth_consumer='%s'", array(
        ':oauth_consumer' => $consumer_token->key,
      ));
    $server = db_fetch_array($res);

    // If it we got a access token for one of our consumers
    if ($server) {
      // Update the server with the access token key and redirect to
      // the conglomerateclient index page.
      $server['oauth_token_key'] = $access_token->key;
      drupal_write_record('conglomerateclient_server', $server, array('sid'));
      drupal_goto('admin/settings/conglomerateclient/index');
    }
  }
}

/**
 * Gets the registered conglomerate servers on the system.
 *
 * @return array
 *  An array withe server information keyed by site id.
 */
function conglomerateclient_get_servers() {
  $servers = array();
  $res = db_query("SELECT * FROM {conglomerateclient_server}");
  while ($server = db_fetch_array($res)) {
    $servers[$server['sid']] = $server;
  }
  return $servers;
}

/**
 * Returns a exportable array for the given server.
 *
 * @param int $sid
 *  The id of the server
 * @return array
 */
function conglomerateclient_export_server($sid) {
  $servers = conglomerateclient_get_servers();
  $export = array();

  if ($servers[$sid]) {
    $server = $servers[$sid];
    unset($server['sid']);
    $export['conglomerateclient_server'] = $server;
    $cred = _conglomerateclient_credentials($sid);
    if ($cred) {
      $export['oauth_common_consumer_token'] = (array)$cred['consumer'];
      $export['oauth_common_token'] =(array)$cred['token'];
    }
  }

  return $export;
}

function _conglomerateclient_admin_export_server($form_state, $sid) {
  $export = conglomerateclient_export_server($sid);
  $form = array();
  $form['body'] = array(
    '#type' => 'textarea',
    '#title' => t('Exported server'),
    '#cols' => 60,
    '#rows' => 30,
    '#value' => "<?php\n// Export of the client information for the conglomerate server \"{$export['conglomerateclient_server']['name']}\"\n\n" . var_export($export, TRUE),
  );
  return $form;
}

/**
 * Adds a conglomerate server
 *
 * @param string $name
 *  The name of the server.
 * @param string $url
 *  A url to the server. Typically to the front page.
 * @param string $endpoint
 *  The endpoint for the api on the server.
 * @param string $login_consumer_key
 *  The key for the consumer to use when logging in users.
 * @param string $consumer_key
 *  The key for the consumer to use when communicating with the server.
 * @param string $access_key
 *  The key for the access token to use when communicating with the server.
 * @return int
 *  The id of the created server
 */
function conglomerateclient_add_server($name, $url, $endpoint, $login_consumer_key, $consumer_key, $access_key) {
  $values = array(
    'name' => $name,
    'url' => $url,
    'endpoint' => $endpoint,
    'login_oauth_consumer' => $login_consumer_key,
    'oauth_consumer' => $consumer_key,
    'oauth_token_key' => $access_key,
  );
  drupal_write_record('conglomerateclient_server', $values);
  return db_last_insert_id('conglomerateclient_server', 'sid');
}

/**
 * Updates a conglomerate server
 *
 * @param int $sid
 *  The id of the server to update.
 * @param string $name
 *  The name of the server.
 * @param string $url
 *  A url to the server. Typically to the front page.
 * @param string $endpoint
 *  The endpoint for the api on the server.
 * @param string $login_consumer_key
 *  The key for the consumer to use when logging in users.
 * @param string $consumer_key
 *  The key for the consumer to use when communicating with the server.
 * @param string $access_key
 *  The key for the access token to use when communicating with the server.
 * @return void
 */
function conglomerateclient_update_server($sid, $name, $url, $endpoint, $login_consumer_key, $consumer_key, $access_key) {
  $values = array(
    'sid' => $sid,
    'name' => $name,
    'url' => $url,
    'endpoint' => $endpoint,
    'login_oauth_consumer' => $login_consumer_key,
    'oauth_consumer' => $consumer_key,
    'oauth_token_key' => $access_key,
  );
  drupal_write_record('conglomerateclient_server', $values, array('sid'));
}

/**
 * Get the node synchronization state for a node. You can get the state either
 * for a single or many conglomerate servers.
 *
 * @param string $nid
 *  The nid of the node to load state for.
 * @param int $sid
 *  Optional. The conglomerate site to load state for.
 * @return bool
 *  An array of synchronization states keyed after site id
 */
function conglomerateclient_get_node_sync_info($nid, $sid = 0) {
  $state = array();

  if (!$sid) { // Load state for all conglomerate servers
    $res = db_query("SELECT *
      FROM {conglomerateclient_sync_info}
      WHERE nid=%d", array(
        ':nid' => $nid,
    ));
    if ($r = db_fetch_array($res)) {
      $state[$r['sid']] = $r;
    }
  }
  else { // Load state for a specific conglomerate server
    $res = db_query("SELECT *
      FROM {conglomerateclient_sync_info}
      WHERE nid=%d AND sid=%d", array(
        ':nid' => $nid,
        ':sid' => $sid,
    ));
    if ($r = db_fetch_array($res)) {
      $state[$sid] = $r;
    }
  }

  return $state;
}

/**
 * Creates or updates the synchronization information for a node.
 *
 * @param string $nid
 *  The nid of the node to set the synchronization information for.
 * @param string $sid
 *  The site id of the synchronization information.
 * @param string $eid
 *  Optional. The nid of the node on the conglomerate site.
 * @return void
 */
function conglomerateclient_set_node_sync_info($nid, $sid, $eid = 0) {
  $rv = conglomerateclient_get_servers();
  $current = conglomerateclient_get_node_sync_info($node->nid, $sid);
  $update = empty($current) ? NULL : array('sid', 'nid');

  $state = array(
    'nid' => $nid,
    'sid' => $sid,
    'updated' => time(),
  );
  if ($eid) {
    $state['eid'] = $eid;
  }

  drupal_write_record('conglomerateclient_sync_info', $state, $update);
}

/**
 * Deletes synchronization information for a node.
 *
 * @param string $nid
 *  The nid of the node to remove the synchronization information for.
 * @param string $sid
 *  The site id of the synchronization information.
 * @return void
 */
function conglomerateclient_delete_node_sync_info($nid, $sid) {
  db_query("DELETE FROM {conglomerateclient_sync_info} WHERE nid=%d AND sid=%d", array(
      ':nid' => $nid,
      ':sid' => $sid,
    ));
}

/**
 * Implementation of hook_nodeapi().
 **/
function conglomerateclient_nodeapi(&$node, $op, $a3 = NULL, $page = NULL) {
  switch ($op) {
    case 'delete':
    case 'insert':
    case 'update': // TODO: Check that revision delete results in a update call
      // We just mark the node as dirty here. We can't be sure that all node
      // information has been saved. Therefore we can't execute the
      // aggregation selection views.
      conglomerateclient_mark_node_as_dirty($node->nid);
    break;
  }
}

/**
 * Implementation of hook_exit();
 */
function conglomerateclient_exit() {
  // Get the nodes that have been marked as dirty during this request
  $dirty = conglomerateclient_mark_node_as_dirty();
  if (!empty($dirty)) {
    $max_ad_hoc = variable_get('conglomerateclient_maximum_adhoc_updates', 3);
    if (count($dirty)>$max_ad_hoc) {
      $dirty = array_slice($dirty, 0, $max_ad_hoc);
    }
    conglomerateclient_process_nodes($dirty);
    conglomerateclient_sync_nodes($dirty);
  }
}

/**
 * Implementation of hook_cron().
 */
function conglomerateclient_cron() {
  $max_updates = variable_get('conglomerateclient_maximum_cron_updates', 20);
  $dirty = conglomerateclient_get_dirty_nodes($max_updates);
  conglomerateclient_process_nodes($dirty);
  conglomerateclient_sync_nodes();

  // For all users; upload roles to main server
  $users = db_query('SELECT uid FROM {users}');
  while ($user = db_fetch_object($users)) {
    _conglomerateclient_upload_roles($users->uid, FALSE);
  }
}

/**
 * Marks a node as dirty.
 *
 * @param int $nid
 *  The nid of the node that should be queued.
 * @return array
 *  An array of nodes that have been marked as dirty during this request.
 */
function conglomerateclient_mark_node_as_dirty($nid = NULL) {
  global $db_type;
  static $queue;

  if (!$queue) {
    $queue = array();
  }

  if ($nid) {
    // Queue the node so that we can sync it on exit
    $queue[] = $nid;
    if ($db_type == 'mysql') {
      // We can do the insert in one statement if we're on mysql
      db_query("INSERT INTO {conglomerateclient_node_dirty} VALUES(%d)
        ON DUPLICATE KEY IGNORE", array(':nid' => $nid));
    }
    else {
      // Check if we need to do a insert before adding a dirty flag
      $exists = db_result(db_query("SELECT COUNT(nid)
        FROM {conglomerateclient_node_dirty} WHERE nid=%d",array(
          ':nid' => $nid,
        )));
      if (!$exists) {
        db_query("INSERT INTO {conglomerateclient_node_dirty} VALUES(%d)", array(':nid' => $nid));
      }
    }
  }

  return $queue;
}

function conglomerateclient_get_dirty_nodes($limit = 0) {
  if ($limit) {
    $res = db_query_range("SELECT nid FROM {conglomerateclient_node_dirty}", 0, $limit);
  }
  else {
    $res = db_query_range("SELECT nid FROM {conglomerateclient_node_dirty}");
  }

  $dirty = array();
  while ($nid = db_result($res)) {
    $dirty[] = $nid;
  }

  return $dirty;
}

/**
 * Processes nodes to check if updates should be sent to the servers.
 * Nodes that should be synchronized are appended to the work queue.
 *
 * @param array $nodes
 *  An array of nid:s for the nodes that should be updated.
 * @return void
 */
function conglomerateclient_process_nodes($nodes) {
  foreach ($nodes as $nid) {
    $sync = conglomerateclient_evaluate_node($nid);
    $status = conglomerateclient_get_node_sync_info($nid);

    // Queue updates and deletes
    foreach ($sync as $sid => $data) {
      if (isset($status[$sid])) {
        conglomerateclient_queue_operation($nid, $sid, 'update', $data);
      }
      else {
        conglomerateclient_set_node_sync_info($nid, $sid);
        conglomerateclient_queue_operation($nid, $sid, 'create', $data);
      }
    }
    // Queue deletes
    foreach ($status as $sid => $info) {
      if (!isset($sync[$sid])) {
        conglomerateclient_queue_operation($nid, $sid, 'delete', $info);
      }
    }
  }
  // Remove the dirty state for queued nodes
  if (!empty($nodes)) {
    $placeholders = db_placeholders($nodes);
    db_query("DELETE FROM {conglomerateclient_node_dirty}
      WHERE nid IN({$placeholders})", $nodes);
  }
}

/**
 * Adds a synchronization operation to the queue.
 *
 * @param int $nid
 * @param int $sid
 * @param string $operation
 * @param mixed $data
 * @return void
 */
function conglomerateclient_queue_operation($nid, $sid, $operation, $data) {
  $values = array(
    'sid' => $sid,
    'nid' => $nid,
    'operation' => $operation,
    'data' => $data,
    'added' => time(),
  );
  drupal_write_record('conglomerateclient_queue', $values);
}

/**
 * Implementation of hook_block().
 */
function conglomerateclient_block($op = 'list', $delta = 0, $edit = array()) {
  global $language;

  switch ($op) {

    case 'list':
      $blocks = array();
      $blocks['nearby'] = array(
        'info' => t('Nearby'),
      );
      return $blocks;

    case 'configure':
      $form = array();
      return $form;

    case 'save':
      break;

    case 'view':
      $block = array();

      switch ($delta) {
        case 'nearby':
          $block['content'] = _conglomerateclient_solrblock();
          break;
      }

      return $block;
  }
}

function conglomerateclient_search_blocks() {
  global $language;
  $cached = cache_get('conglomerateclient:search_blocks:' . $language->language);
  if ($cached && $cached->data) {
    $blocks = $cached->data;
  }
  else {
    $blocks = array();
    $credentials = _conglomerateclient_credentials(1);

    if ($credentials) {
      $server = $credentials['server'];
      $auth = new RestClientOAuth($credentials['consumer']);
      $client = new RestClient($auth, new RestClientBaseFormatter());

      $blocks = $res = $client->get($server['endpoint'] . '/block.php', array(
        'language' => $language->language,
      ));
    }

    cache_set('conglomerateclient:search_blocks:' . $language->language, $blocks, 'cache', strtotime('+10 minute'));
  }
  return $blocks;
}

function _conglomerateclient_solrblock() {
  global $language;
  $content = NULL;
  $cached = cache_get('conglomerateclient:search_blocks_content:' . $language->language);

  if ($cached && $cached->data) {
    $content = $cached->data;
  }
  else {
    $credentials = _conglomerateclient_credentials(1);
    if ($credentials) {
      $server = $credentials['server'];
      $auth = new RestClientOAuth($credentials['consumer']);
      $client = new RestClient($auth, new RestClientBaseFormatter());

      $blocks = conglomerateclient_search_blocks();
      $content = '';

      $title_lookup = array();
      foreach ($blocks as $block) {
        $query = array(
          'type' => array(
            '#type' => 'aggregate',
            '#operator' => 'or',
            'values' => array('event','news','location'),
          ),
          'tid' => array(
            '#type' => 'aggregate',
            '#operator' => 'and',
          ),
          'language' => $language->language,
        );

        foreach ($block['terms'] as $term) {
          $query['tid']['values'][] = $term[0];
        }
        try {
          $res = $client->get($server['endpoint'] . '/search.php', array(
            'query' => conglomerateclient_query($query),
            'fields' => 'title,ss_node_page_url,ss_node_image_url',
            'inside_area' => 'yes',
            'sort' => 'created desc',
            'rows' => 4,
          ));
          $links = array();
          foreach ($res['items'] as $node) {
            if (!isset($title_lookup[$node['title']])) {
              $links[] = array(
                'title' => $node['title'],
                'href' => $node['ss_node_page_url'],
                'image' => $node['ss_node_image_url'],
              );
              $title_lookup[$node['title']] = TRUE;
            }
          }
          if (!empty($links)) {
            // Get us a even count of items.
            if (count($links) > 4) {
              $links = array_slice($links, 0, 4);
            }
            else if (count($links) > 1 && count($links) % 2) {
              array_splice($links, count($links)-1, 2);
            }

            $content .= '<h3>' . $block['title'] . '</h3>';
            $content .= theme('conglomerate_nearby_links', $links);
          }
        }
        catch (Exception $e) {
        }
      }
    }
    cache_set('conglomerateclient:search_blocks_content:' . $language->language, $content, 'cache', strtotime('+10 minute'));
  }

  return $content;
}

function conglomerateclient_query($def) {
  return _conglomerateclient_qb(NULL, $def);
}

function _conglomerateclient_qb($key, $def) {
  $types = array(
    'aggregate' => '_conglomerateclient_qb_aggregate',
  );
  $c = array();
  foreach (element_children($def) as $k) {
    $cdef = $def[$k];
    if (isset($cdef['#type']) && !empty($types[$cdef['#type']])) {
      $c[] = call_user_func($types[$cdef['#type']], $k, $cdef);
    }
    else if (is_array($cdef)) {
      $c[] = _conglomerateclient_qb($k, $cdef);
    }
    else {
      $c[] = $k . ':' . $def[$k];
    }
  }
  return _conglomerateclient_qb_join($def, $c);
}

function _conglomerateclient_qb_aggregate($key, $def) {
  $q = array();
  foreach ($def['values'] as $v) {
    $q[] = $key . ':' . $v;
  }
  return _conglomerateclient_qb_join($def, $q);
}

function _conglomerateclient_qb_join($def, $values) {
  $op = ' AND ';
  if ($def['#operator'] == 'or') {
    $op = ' OR ';
  }
  return '(' . join($values, $op) . ')';
}

function conglomerateclient_sync_nodes($nodes=array()) {
  if (!empty($nodes)) {
    $placeholders = db_placeholders($nodes);
    $res = db_query("SELECT q.*, i.eid FROM {conglomerateclient_queue} AS q
      INNER JOIN {conglomerateclient_sync_info} AS i ON (i.sid=q.sid AND i.nid=q.nid)
      WHERE q.nid IN({$placeholders}) AND i.in_progress = 0
      ORDER BY q.sid, q.nid, q.added", $nodes);
  }
  else {
    $res = db_query("SELECT q.*, i.eid FROM {conglomerateclient_queue} AS q
      INNER JOIN {conglomerateclient_sync_info} AS i ON (i.sid=q.sid AND i.nid=q.nid)
      WHERE i.in_progress = 0
      ORDER BY q.sid, q.nid, q.added");
  }

  $in_progress = array();
  $sync = array();
  while ($a = db_fetch_array($res)) {
    $sync[$a['sid']][$a['nid']][] = $a;
  }

  // Mark the nodes as in-progress
  foreach ($sync as $sid => $updates) {
    $params = array_keys($updates);
    $placeholders = db_placeholders($params);
    $params = array_merge(array($sid), $params);
    db_query("UPDATE {conglomerateclient_sync_info} SET in_progress = 1
      WHERE sid=%d AND nid IN({$placeholders})", $params);
  }

  // Successful operation ID:s
  $opids = array();
  // Failed operation ID:s
  $fopids = array();

  try {
    // Run through and execute the queued operations
    foreach ($sync as $sid => $updates) {
      foreach ($updates as $nid => $ops) {
        // Remove redundant operations
        _conglomerateclient_compress_node_ops($ops);

        $last_success = FALSE;
        for ($i=0; $i<count($ops); $i++) {
          if ($ops[$i]) {
            $success = _conglomerateclient_perform_operation($ops[$i]);
            if ($success) {
              $opids[] = $ops[$i]['id'];
            }
            else {
              $fopids[] = $ops[$i]['id'];
              break;
            }
          }
        }
      }
    }
  }
  catch (Exception $e) {
    watchdog('conglomerateclient', 'An error occured while pushing updates: [@code] @message', array(
      '@code' => $e->getCode(),
      '@message' => $e->getMessage(),
    ), WATCHDOG_ERROR);
  }

  // Delete the operations that were successful.
  if (!empty($opids)) {
    $placeholders = db_placeholders($opids);
    db_query("DELETE FROM {conglomerateclient_queue}
      WHERE id IN({$placeholders})", $opids);
  }
  // Increas fail count the operations that were unsuccessful.
  if (!empty($fopids)) {
    $placeholders = db_placeholders($fopids);
    db_query("UPDATE {conglomerateclient_queue}
      SET fail_count = fail_count + 1
      WHERE id IN({$placeholders})", $fopids);
  }

  // Mark the nodes as processed
  foreach ($sync as $sid => $updates) {
    $params = array_keys($updates);
    $placeholders = db_placeholders($params);
    $params = array_merge(array($sid), $params);
    db_query("UPDATE {conglomerateclient_sync_info} SET in_progress = 0
      WHERE sid=%d AND nid IN({$placeholders})", $params);
  }
}

/**
 * The task of this function is to remove unnecessary operations. Multiple
 * consequetive updates can be reduced to just the last update. Updates
 * preceding a delete can be skipped altogether.
 *
 * @param array $ops
 * @return void
 */
function _conglomerateclient_compress_node_ops(&$ops) {
  $opc = count($ops);
  if ($opc > 1 && $ops[0]['operation'] == 'create' && $ops[$opc-1]['operation'] == 'delete') {
    array_splice($ops, 0, $opc);
    return;
  }

  $last_op = FALSE;
  for ($i=0; $i<count($ops); $i++) {
    if ($ops[$i]['operation'] == 'delete' || $ops[$i]['operation'] == 'update') {
      if ($last_op == 'update') {
        array_splice($ops, $i-1, 1);
        $i--;
      }
    }
    $last_op = $ops[$i]['operation'];
  }
}

/**
 * Gets the view names and display Id's for the views and displays that can be
 * used to determine if a node should be synced.
 *
 * @param string $content_type
 * @return array
 */
function conglomerateclient_sync_views($content_type) {
  $cached = cache_get('conglomerateclient:views:' . $content_type);
  if (FALSE && $cached && $cached->data) {
    $sync_views = $cached->data;
  }
  else {
    $sync_views = array();
    foreach (views_get_all_views() as $view) {
      foreach ($view->display as $display_id => $display) {
        if ($display->display_plugin == 'sync' && $display->display_options['content_type'] == $content_type) {
          $sync_views[$view->name][] = $display_id;
        }
      }
    }
    cache_set('conglomerateclient:views:' . $content_type, $sync_views, 'cache', CACHE_TEMPORARY);
  }

  return $sync_views;
}

/**
 * Filter node through view to determine if and what to synchronize.
 */
function conglomerateclient_evaluate_node($nid) {
  if (!$node = node_load($nid)) return array();
  $result = array();

  $servers = conglomerateclient_get_servers();

  $views = conglomerateclient_sync_views($node->type);
  foreach ($views as $view_name => $displays) {
    $view = views_get_view($view_name);
    if ($view->disabled) {
      continue;
    }
    foreach ($displays as $display_id) {
      $display = $view->display[$display_id];
      $server = $display->display_options['server'];
      // Check that a server has been specified and that it exists
      if (empty($server) || !isset($servers[$server])) {
        continue;
      }

      // We stop executing views for servers that we already have a match for
      if (!isset($result[$server])) {
        $view->execute_display($display_id, array($node->nid));
        $view_result = reset($view->result);
        if ($view_result) {
          $row = array(
            'type' => $display->display_options['server_type'],
            'fulltext' => '',
          );
          foreach ($display->display_options['fields_mapping'] as $key => $value) {
            if ($key == 'starts') {
              $rendered = $view->style_plugin->rendered_fields[0][$value];
              $captured = array();
              $timestamps = array();
              if (preg_match_all('/\[{2}(\d+)\]{2}/', $rendered, $captured)) {
                foreach ($captured[1] as $match) {
                  $timestamps[] = $match;
                }
              }
              $row[$key] = $timestamps;
            }
            else {
              $row[$key] = $view->style_plugin->rendered_fields[0][$value];
            }
          }

          // Add the url to the node as default to the url field
          if (empty($row['url'])) {
            $row['url'] = url('node/' . $node->nid, array(
              'absolute' => TRUE,
            ));
          }
          // Add the node language if not set
          if (empty($row['language'])) {
            $row['language'] = $node->language;
          }

          drupal_alter('conglomerateclient_data', $row, $node);

          $result[$server] = $row;
        }
      }
    }
  }
  return $result;
}

function _conglomerateclient_perform_operation($op) {
  $data = unserialize($op['data']);

  $result = FALSE;
  $credentials = _conglomerateclient_credentials($op['sid']);

  if ($credentials) {
    $server = $credentials['server'];
    $auth = new RestClientOAuth($credentials['consumer'], $credentials['token'], new OAuthSignatureMethod_HMAC_SHA1());
    $client = new RestClient($auth, new RestClientBaseFormatter());

    try {
      switch ($op['operation']) {
        case 'create':
          $res = $client->post($server['endpoint'] . '/content.php', $data);
          if ($res && isset($res->nid)) {
            db_query("UPDATE {conglomerateclient_sync_info} SET eid = %d
              WHERE sid=%d AND nid = %d", array(
                ':eid' => $res->nid,
                ':sid' => $op['sid'],
                ':nid' => $op['nid'],
              ));
            $result = TRUE;
          }
          break;
        case 'update':
          $res = $client->put($server['endpoint'] . '/content/' . $op['eid'] . '.php', $data);
          $result = $res && isset($res->nid);
          break;
        case 'delete':
          $res = $client->delete($server['endpoint'] . '/content/' . $op['eid'] . '.php', $data);
          if ($res) {
            conglomerateclient_delete_node_sync_info($op['nid'], $op['sid']);
            $result = TRUE;
          }
          break;
      }
    }
    catch (Exception $e) {
      watchdog('conglomerateclient', 'An error occured while pushing updates: [@code] @message. Response: @response', array(
        '@code' => $e->getCode(),
        '@message' => $e->getMessage(),
        '@response' => $client->rawResponse,
      ), WATCHDOG_ERROR);
      $result = FALSE;
    }
  }

  return $result;
}

function _conglomerateclient_credentials($server) {
  static $static_credentials;

  $credentials = FALSE;
  if (!isset($credentials[$server])) {
    $servers = conglomerateclient_get_servers();
    if (isset($servers[$server])) {
      $s = $servers[$server];
      if (!empty($s['oauth_consumer']) && !empty($s['oauth_token_key'])) {
        $consumer = DrupalOAuthConsumerToken::load($s['oauth_consumer']);
        $token = DrupalOAuthToken::load($s['oauth_token_key']);
        if ($consumer && $token) {
          $credentials = array(
            'server' => $s,
            'consumer' => $consumer,
            'token' => $token,
          );
        }
      }
    }
    $static_credentials[$server] = $credentials;
  }
  else {
    $credentials = $static_credentials[$server];
  }

  return $credentials;
}

/**
 * Implementation of Hook_User().
 */
function conglomerateclient_user($op, &$edit, &$account, $category = NULL) {
  switch($op) {
    case 'after_update':
    case 'insert':
    case 'update':
    case 'login':
      _conglomerateclient_upload_roles($account->uid, FALSE);
      break;

    case 'delete':
      _conglomerateclient_upload_roles($account->uid, TRUE);
      break;
  }
}

/**
 * Uploads user roles to the main server
 */
function _conglomerateclient_upload_roles($uid, $delete=FALSE) {
  if (class_exists('RestClient')) {
    $client = new RestClient();

    $servers = conglomerateclient_get_servers();
    $server = $servers[variable_get('conglomerateclient_login_server', 1)];
    $auth = new RestClientOAuth(DrupalOAuthConsumerToken::load($server['oauth_consumer']), DrupalOAuthToken::load($server['oauth_token_key']), new OAuthSignatureMethod_HMAC_SHA1());
    $client->setAuthentication($auth);
    $client->setFormatter(new RestClientBaseFormatter());

    // Get external ID
    $userskane = db_query('SELECT euid FROM {conglomerate_users} WHERE uid=%d LIMIT 1', $uid);
    $userskane = db_fetch_object($userskane);
    $data['euid'] = $userskane->euid;

    $user = user_load($uid);

    // Get roles, send empty array if user should be removed
    $data['roles'] = $delete ? array() : $user->roles;

    // Tell server to delete/update roles
    try {
      $maxTries = 2;
      $tries = 0;
      $response = $client->post($server['endpoint'] . '/user/roleUpdate.php', $data);
      while ($response->error === TRUE) {
        $tries++;
        if ($tries >= $maxTries) {
          break;
        }
        $response = $client->post($server['endpoint'] . '/user/roleUpdate.php', $data);
      }
    } catch (Exception $e) {
      watchdog('conglomerateclient', 'An error occured while pushing roles: [@code] @message', array(
        '@code' => $e->getCode(),
        '@message' => $e->getMessage(),
      ), WATCHDOG_ERROR);
    }
  }
}

function conglomerateclient_field_formatter_info() {
  return array(
    'export_time' => array(
      'label' => t('Export time'),
      'field types' => array('date', 'datestamp', 'datetime'),
    ),
  );
}

/**
 * Theme function to display showtimes.
 */
function theme_conglomerateclient_formatter_export_time($element) {
  $start_date = strtotime($element['#item']['value']);
  return '[[' . date('U', $start_date) . ']]';
}
